apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
    namespace: vegait-training 
stringData:
    POSTGRES_DATABASE: {{ .Values.secret.db }}
    POSTGRES_USER: {{ .Values.secret.user }}
    POSTGRES_PASSWORD: {{ .Values.secret.password }}