apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-service
    namespace: vegait-training     
spec:
    selector:
        app: {{ .Values.label }}
    ports:
        - protocol: {{ .Values.service.protocol }}
          port: {{ .Values.service.port }}
          targetPort: {{ .Values.service.target_port }}
